(base) PS C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker> .\venv\Scripts\activate                      (venv) (base) PS C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker> python .\main.py                      Loading trash detection model...                                                                                         * Serving Flask app 'app'                                                                                               * Debug mode: on                                                                                                       INFO:werkzeug:←[31m←[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.←[0m                                                                                                * Running on all addresses (0.0.0.0)                                                                                    * Running on http://127.0.0.1:5000                                                                                      * Running on http://192.168.6.110:5000                                                                                 INFO:werkzeug:←[33mPress CTRL+C to quit←[0m                                                                             INFO:werkzeug: * Restarting with stat                                                                                   Loading trash detection model...                                                                                        Traceback (most recent call last):                                                                                        File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__                                                                                                    self._dbapi_connection = engine.raw_connection()                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^                                                                      File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3298, in raw_connection                                                                                             return self.pool.connect()                                                                                                     ^^^^^^^^^^^^^^^^^^^                                                                                            File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect                                                                                                       return _ConnectionFairy._checkout(self)                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                               File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout                                                                                                    fairy = _ConnectionRecord.checkout(pool)                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                              File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout                                                                                                      rec = pool._do_get()                                                                                                          ^^^^^^^^^^^^^^                                                                                                  File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get                                                                                                       with util.safe_reraise():                                                                                             File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__                                                                                               raise exc_value.with_traceback(exc_tb)                                                                                File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get                                                                                                       return self._create_connection()                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                      File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection                                                                                            return _ConnectionRecord(self)                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^                                                                                        File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__                                                                                                      self.__connect()                                                                                                      File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect                                                                                                     with util.safe_reraise():                                                                                             File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__                                                                                               raise exc_value.with_traceback(exc_tb)                                                                                File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect                                                                                                     self.dbapi_connection = connection = pool._invoke_creator(self)                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect                                                                                                   return dialect.connect(*cargs, **cparams)                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                             File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect                                                                                                  return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                 sqlite3.OperationalError: unable to open database file                                                                                                                                                                                          The above exception was the direct cause of the following exception:                                                                                                                                                                            Traceback (most recent call last):                                                                                        File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\main.py", line 1, in <module>                       from app import app                                                                                                   File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\app.py", line 52, in <module>                       db.create_all()                                                                                                       File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 900, in create_all                                                                                              self._call_for_binds(bind_key, "create_all")                                                                          File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 881, in _call_for_binds                                                                                         getattr(metadata, op_name)(bind=engine)                                                                               File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5925, in create_all                                                                                                  bind._run_ddl_visitor(                                                                                                File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3248, in _run_ddl_visitor                                                                                           with self.begin() as conn:                                                                                            File "C:\Users\asus\anaconda3\Lib\contextlib.py", line 137, in __enter__                                                  return next(self.gen)                                                                                                          ^^^^^^^^^^^^^^                                                                                                 File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3238, in begin                                                                                                      with self.connect() as conn:                                                                                                 ^^^^^^^^^^^^^^                                                                                                   File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3274, in connect                                                                                                    return self._connection_cls(self)                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                     File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 148, in __init__                                                                                                    Connection._handle_dbapi_exception_noconnection(                                                                      File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2439, in _handle_dbapi_exception_noconnection                                                                       raise sqlalchemy_exception.with_traceback(exc_info[2]) from e                                                         File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__                                                                                                    self._dbapi_connection = engine.raw_connection()                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^                                                                      File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3298, in raw_connection                                                                                             return self.pool.connect()                                                                                                     ^^^^^^^^^^^^^^^^^^^                                                                                            File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect                                                                                                       return _ConnectionFairy._checkout(self)                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                               File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout                                                                                                    fairy = _ConnectionRecord.checkout(pool)                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                              File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout                                                                                                      rec = pool._do_get()                                                                                                          ^^^^^^^^^^^^^^                                                                                                  File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get                                                                                                       with util.safe_reraise():                                                                                             File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__                                                                                               raise exc_value.with_traceback(exc_tb)                                                                                File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get                                                                                                       return self._create_connection()                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                      File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection                                                                                            return _ConnectionRecord(self)                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^                                                                                        File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__                                                                                                      self.__connect()                                                                                                      File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect                                                                                                     with util.safe_reraise():                                                                                             File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__                                                                                               raise exc_value.with_traceback(exc_tb)                                                                                File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect                                                                                                     self.dbapi_connection = connection = pool._invoke_creator(self)                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect                                                                                                   return dialect.connect(*cargs, **cparams)                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                             File "C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect                                                                                                  return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file                                (Background on this error at: https://sqlalche.me/e/20/e3q8)                                                            (venv) (base) PS C:\Users\asus\Downloads\OceanWasteTracker (1)\OceanWasteTracker>  